### ISSUE TITLE
在主页支持拖放或者禁止拖放

### ISSUE THREAD

**Issue by RoyRao2333** [ovnrain/netease-music-cloud-uploader#10]
在云盘列表（App主界面）时，从Finder拖动音乐文件进入，则会开始播放：

<img width="1003" alt="image" src="https://github.com/ovnrain/netease-music-cloud-uploader/assets/31413093/d74abb1d-d46d-4afa-9131-51eeda306bb7">

但是播放页面无法退出，无法操作。希望在列表时支持拖放后跳转上传界面，或直接禁止拖放。

**Comment by ovnrain** [comment]
[v1.2.1](https://github.com/ovnrain/netease-music-cloud-uploader/releases/tag/v1.2.1) 已修复，禁止拖放
