### ISSUE TITLE
上传下载好的音乐提示歌曲发布错误

### ISSUE THREAD

**Issue by tasselx** [ovnrain/netease-music-cloud-uploader#2]
![image](https://user-images.githubusercontent.com/2656142/230574380-485d9e76-9df1-4754-a580-a3746dbef77c.png)

**Comment by ovnrain** [comment]
文件发我试试，issue 回复框可以添加附件

**Comment by tasselx** [comment]
https://user-images.githubusercontent.com/2656142/230642888-93e97802-2662-4664-850f-117e205e95b7.mp4
不支持上传mp3格式文件，我把文件后缀名改为了mp4你下载后可以恢复下 @ovnrain

**Comment by ovnrain** [comment]
研究了一下，接口返回错误，不知道啥原因
给你这个吧 [Billie Eilish - Six Feet Under.mp3.zip](https://github.com/ovnrain/netease-music-cloud-uploader/files/11181145/Billie.Eilish.-.Six.Feet.Under.mp3.zip)

**Comment by tasselx** [comment]
> 研究了一下，接口返回错误，不知道啥原因 给你这个吧 [Billie Eilish - Six Feet Under.mp3.zip](https://github.com/ovnrain/netease-music-cloud-uploader/files/11181145/Billie.Eilish.-.Six.Feet.Under.mp3.zip)

好的，谢谢，我先换这个，另外可以上传可以加上拖拽上传吗😂，每次打开页面都条件反射的拖过去

**Comment by ovnrain** [comment]
> > 研究了一下，接口返回错误，不知道啥原因 给你这个吧 [Billie Eilish - Six Feet Under.mp3.zip](https://github.com/ovnrain/netease-music-cloud-uploader/files/11181145/Billie.Eilish.-.Six.Feet.Under.mp3.zip)
> 
> 好的，谢谢，我先换这个，另外可以上传可以加上拖拽上传吗😂，每次打开页面都条件反射的拖过去

研究了一下，拖拽文件在 Tauri 有很多问题，先不弄了
https://github.com/tauri-apps/tauri/discussions/4736
https://github.com/tauri-apps/tauri/issues/2593

**Comment by ovnrain** [comment]
> > 研究了一下，接口返回错误，不知道啥原因 给你这个吧 [Billie Eilish - Six Feet Under.mp3.zip](https://github.com/ovnrain/netease-music-cloud-uploader/files/11181145/Billie.Eilish.-.Six.Feet.Under.mp3.zip)
> 
> 好的，谢谢，我先换这个，另外可以上传可以加上拖拽上传吗😂，每次打开页面都条件反射的拖过去

最新版本已支持
