### ISSUE TITLE
云盘歌曲显示不完整

### ISSUE THREAD

**Issue by tasselx** [ovnrain/netease-music-cloud-uploader#3]
![image](https://user-images.githubusercontent.com/2656142/230816071-82a0cc7c-4b49-45a5-ba59-022a1db744ff.png)

![image](https://user-images.githubusercontent.com/2656142/230816115-299174d6-c58e-448f-82fd-5ef519d3a74e.png)

在我云盘实际有2000+歌曲，但是这里只显示了1000，是因为没做分页吗？

**Comment by ovnrain** [comment]
新版已修复 [v1.0.3](https://github.com/ovnrain/netease-music-cloud-uploader/releases/tag/v1.0.3)
也可打开现有版本自动更新
